const events = [
  { title: 'Paper Presentation', type: 'technical', kicker: 'TECHNICAL / 01—03 MEMBERS', prize: '₹10,000 + Trophy', day: 'Day 01', blurb: 'Defend a sharp idea in VLSI, signal processing, AI, or connected systems.', image: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=900&q=85' },
  { title: 'Project Expo', type: 'technical', kicker: 'TECHNICAL / 02—04 MEMBERS', prize: '₹12,000 + Trophy', day: 'Day 01', blurb: 'Put your working prototype on the table and let the engineering speak.', image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=900&q=85' },
  { title: 'Circuit Debugging', type: 'technical', kicker: 'TECHNICAL / 01—02 MEMBERS', prize: '₹6,000 + Trophy', day: 'Day 02', blurb: 'Trace the fault, read the waveform, and bring a broken circuit back to life.', image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=85' },
  { title: 'Coding Sprint', type: 'technical', kicker: 'TECHNICAL / SOLO', prize: '₹8,000 + Badge', day: 'Day 01', blurb: 'Algorithms, time pressure, and the cleanest solution in the room.', image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=900&q=85' },
  { title: 'Robo Combat', type: 'technical', kicker: 'TECHNICAL / 02—04 MEMBERS', prize: '₹15,000 + Shield', day: 'Day 02', blurb: 'Build a machine with enough nerve to survive the arena.', image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=900&q=85' },
  { title: 'ElectroTrivia', type: 'technical', kicker: 'TECHNICAL / 02 MEMBERS', prize: '₹5,000 + Trophy', day: 'Day 01', blurb: 'A buzzer, a room full of signals, and no time to second-guess yourself.', image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=85' },
  { title: 'Signal Challenge', type: 'technical', kicker: 'TECHNICAL / 02 MEMBERS', prize: '₹7,000 + Trophy', day: 'Day 02', blurb: 'Decode, calibrate, and find meaning in the static.', image: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=900&q=85' },
  { title: 'Campus Quest', type: 'non-technical', kicker: 'NON-TECHNICAL / 03—04 MEMBERS', prize: '₹5,000 + Medals', day: 'Day 01', blurb: 'Cryptic clues, hidden coordinates, and a campus seen from a new angle.', image: 'https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?auto=format&fit=crop&w=900&q=85' },
  { title: 'Mega Auction', type: 'non-technical', kicker: 'NON-TECHNICAL / 02—03 MEMBERS', prize: '₹5,000 + Trophy', day: 'Day 02', blurb: 'Build your dream team while the room watches every move.', image: 'https://images.unsplash.com/photo-1531415074868-036b1c57e329?auto=format&fit=crop&w=900&q=85' },
  { title: 'Connections', type: 'non-technical', kicker: 'NON-TECHNICAL / 02 MEMBERS', prize: '₹3,000 + Prize', day: 'Day 01', blurb: 'Link images, ideas, and pop-culture fragments faster than your rivals.', image: 'https://images.unsplash.com/photo-1606326608606-aa0b62935f2b?auto=format&fit=crop&w=900&q=85' },
  { title: 'Tech Debate', type: 'non-technical', kicker: 'NON-TECHNICAL / 01—02 MEMBERS', prize: '₹4,000 + Memento', day: 'Day 02', blurb: 'Take a position on the technology shaping tomorrow, then defend it.', image: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=900&q=85' },
  { title: 'Fest Photography', type: 'spot', kicker: 'SPOT / SOLO', prize: '₹3,000 + Feature', day: 'Both days', blurb: 'Catch the frame that makes the whole festival feel alive.', image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=900&q=85' },
  { title: 'Meme Circuit', type: 'spot', kicker: 'SPOT / SOLO', prize: '₹2,000 + Prize', day: 'Day 01', blurb: 'Turn engineering pain, lab lore, and campus life into sharp visual comedy.', image: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=900&q=85' },
  { title: 'Reel Craft', type: 'spot', kicker: 'SPOT / 01—02 MEMBERS', prize: '₹3,000 + Prize', day: 'Day 02', blurb: 'Shoot and cut a 30-second burst of PulseFest energy.', image: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?auto=format&fit=crop&w=900&q=85' },
  { title: 'Tech Charades', type: 'spot', kicker: 'SPOT / 02 MEMBERS', prize: '₹2,000 + Prize', day: 'Day 01', blurb: 'Act out the impossible terminology without saying a word.', image: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=900&q=85' },
  { title: 'Mystery Drop', type: 'spot', kicker: 'SPOT / 01—02 MEMBERS', prize: 'Instant cash prize', day: 'Day 02', blurb: 'An unreleased challenge. Show up curious and leave with bragging rights.', image: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=900&q=85' },
  { title: 'Quiz', type: 'non-technical', kicker: 'NON-TECHNICAL / SOLO OR TEAM', prize: 'Trophy + Certificates', day: 'Day 01', blurb: 'A fast, friendly quiz for curious minds across technology, culture, and campus life.', image: 'https://images.unsplash.com/photo-1606326608606-aa0b62935f2b?auto=format&fit=crop&w=900&q=85' },
  { title: 'Photography', type: 'non-technical', kicker: 'NON-TECHNICAL / SOLO', prize: 'Trophy + Certificates', day: 'Both days', blurb: 'Capture the people, colour, and unexpected moments that make the fest memorable.', image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=900&q=85' },
  { title: 'Fashion Walk', type: 'non-technical', kicker: 'NON-TECHNICAL / SOLO OR TEAM', prize: 'Trophy + Certificates', day: 'Day 02', blurb: 'Bring confidence, creativity, and your own point of view to the runway.', image: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=900&q=85' },
  { title: 'Dancing', type: 'non-technical', kicker: 'NON-TECHNICAL / SOLO OR TEAM', prize: 'Trophy + Certificates', day: 'Day 02', blurb: 'Make the stage move with a performance that carries your signature.', image: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=900&q=85' },
  { title: 'Singing', type: 'non-technical', kicker: 'NON-TECHNICAL / SOLO OR TEAM', prize: 'Trophy + Certificates', day: 'Day 02', blurb: 'Take the mic and give the festival a melody it will remember.', image: 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=900&q=85' },
  { title: 'Surprise Events', type: 'non-technical', kicker: 'NON-TECHNICAL / OPEN ENTRY', prize: 'Instant prizes', day: 'Both days', blurb: 'Keep your eyes open: quick-fire games and surprise challenges can appear anywhere.', image: 'https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=900&q=85' }
];

const savedTheme = localStorage.getItem('pulsefest-theme') || 'dark';
document.documentElement.dataset.theme = savedTheme;
const themeToggle = document.querySelector('#theme-toggle');
function updateThemeButton() { const isDark = document.documentElement.dataset.theme === 'dark'; themeToggle.innerHTML = isDark ? '☼ <span>Light</span>' : '☾ <span>Dark</span>'; themeToggle.setAttribute('aria-label', `Switch to ${isDark ? 'light' : 'dark'} theme`); }
themeToggle.addEventListener('click', () => { const nextTheme = document.documentElement.dataset.theme === 'dark' ? 'light' : 'dark'; document.documentElement.dataset.theme = nextTheme; localStorage.setItem('pulsefest-theme', nextTheme); updateThemeButton(); });
updateThemeButton();

const schedule = {
  day1: [['09:00', 'Registration & welcome kit', 'Registration desk / foyer', 'GENERAL'], ['11:30', 'Grand inauguration', 'Main auditorium', 'CEREMONY'], ['12:00', 'Paper presentation / Project Expo', 'Seminar Hall A + Expo Hall', 'TECHNICAL'], ['14:00', 'Networking & lunch break', 'Campus dining commons', 'BREAK'], ['15:00', 'Coding sprint & ElectroTrivia', 'System Center / Lab 2', 'TECHNICAL'], ['17:00', 'Campus quest', 'Campus quadrangle', 'NON-TECHNICAL'], ['19:00', 'Acoustic night', 'Open air theatre', 'CULTURAL']],
  day2: [['09:30', 'Circuit debugging arena', 'ECE hardware lab', 'TECHNICAL'], ['11:00', 'Signal challenge', 'Communication lab', 'TECHNICAL'], ['13:00', 'Robo combat heats', 'Innovation yard', 'TECHNICAL'], ['14:30', 'Mega auction', 'Main auditorium', 'NON-TECHNICAL'], ['16:00', 'Reel craft + Mystery drop', 'Festival grounds', 'SPOT'], ['18:00', 'Awards & valedictory', 'Main auditorium', 'CEREMONY']]
};

const gallery = [
  ['Prototype expositions', 'technical', 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1200&q=85'], ['Robotics in motion', 'technical', 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=900&q=85'], ['Signals on the scope', 'technical', 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=85'], ['The crowd comes alive', 'culture', 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=900&q=85'], ['Ideas on the big screen', 'culture', 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=900&q=85'], ['Champions, finally', 'culture', 'https://images.unsplash.com/photo-1578269174936-2709b6aeb913?auto=format&fit=crop&w=900&q=85']
];

const eventGrid = document.querySelector('#event-grid');
let visibleEventIds = null;
function renderEvents(filter = 'all') {
  const liveEvents = visibleEventIds ? events.filter(event => visibleEventIds.has(event.id)) : events;
  eventGrid.innerHTML = liveEvents.filter(event => filter === 'all' || event.type === filter).map((event, index) => `<article class="event-card reveal" style="--delay:${index * 35}ms"><div class="event-image" style="background-image:url('${event.image}')"><span class="event-number">${String(index + 1).padStart(2, '0')}</span><span class="event-type">${event.type}</span></div><div class="event-body"><p class="eyebrow">${event.kicker}</p><h3>${event.title}</h3><p>${event.blurb}</p><div class="event-footer"><span>${event.prize}</span><button class="details-button" data-event="${events.indexOf(event)}">Details ↗</button></div></div></article>`).join('');
  eventGrid.querySelectorAll('.details-button').forEach(button => button.addEventListener('click', () => openModal(events[button.dataset.event])));
}
renderEvents();
fetch('/api/events').then(response => response.json()).then(serverEvents => { visibleEventIds = new Set(serverEvents.filter(event => event.visible !== false).map(event => event.id)); serverEvents.forEach((serverEvent, index) => { if (!events[index]) return; events[index].id = serverEvent.id || String(index + 1).padStart(2, '0'); ['title', 'type', 'kicker', 'prize', 'day', 'blurb', 'image'].forEach(field => { if (serverEvent[field]) events[index][field] = serverEvent[field]; }); }); renderEvents(); }).catch(() => {});
fetch('/api/settings').then(response => response.json()).then(settings => { document.title = `${settings.festName} | ${settings.branch}`; document.querySelector('#hero-title').innerHTML = settings.heroTitle.replace(' ', '<br>'); document.querySelector('#hero-intro').textContent = settings.heroIntro; }).catch(() => {});
document.querySelectorAll('[data-filter]').forEach(button => button.addEventListener('click', () => { document.querySelectorAll('[data-filter]').forEach(item => item.classList.remove('active')); button.classList.add('active'); renderEvents(button.dataset.filter); }));

function renderSchedule(day = 'day1') { document.querySelector('#schedule-list').innerHTML = schedule[day].map(item => `<article class="schedule-item"><time>${item[0]}</time><div><p class="eyebrow">${item[3]}</p><h3>${item[1]}</h3><p>${item[2]}</p></div><span>↗</span></article>`).join(''); }
renderSchedule();
document.querySelectorAll('[data-day]').forEach(button => button.addEventListener('click', () => { document.querySelectorAll('[data-day]').forEach(item => item.classList.remove('active')); button.classList.add('active'); renderSchedule(button.dataset.day); }));

function renderGallery(filter = 'all') { document.querySelector('#gallery-grid').innerHTML = gallery.filter(item => filter === 'all' || item[1] === filter).map((item, index) => `<figure class="gallery-item gallery-${index + 1}"><img src="${item[2]}" alt="${item[0]}"><figcaption><span>${item[1]}</span><strong>${item[0]}</strong></figcaption></figure>`).join(''); }
renderGallery();
document.querySelectorAll('[data-gallery]').forEach(button => button.addEventListener('click', () => { document.querySelectorAll('[data-gallery]').forEach(item => item.classList.remove('active')); button.classList.add('active'); renderGallery(button.dataset.gallery); }));

const modal = document.querySelector('#event-modal');
function openModal(event) { document.querySelector('#modal-type').textContent = `${event.kicker} / ${event.day}`; document.querySelector('#modal-title').textContent = event.title; document.querySelector('#modal-description').textContent = event.blurb; document.querySelector('#modal-meta').innerHTML = `<span>PRIZE <b>${event.prize}</b></span><span>FORMAT <b>${event.kicker.split(' / ')[1]}</b></span>`; modal.classList.add('open'); modal.setAttribute('aria-hidden', 'false'); }
document.querySelector('.modal-close').addEventListener('click', () => { modal.classList.remove('open'); modal.setAttribute('aria-hidden', 'true'); });
modal.addEventListener('click', event => { if (event.target === modal) modal.classList.remove('open'); });

document.querySelector('.menu-toggle').addEventListener('click', () => document.querySelector('.nav-links').classList.toggle('open'));
document.querySelectorAll('.nav-links a').forEach(link => link.addEventListener('click', () => document.querySelector('.nav-links').classList.remove('open')));
const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) entry.target.classList.add('is-visible'); }), { threshold: 0.12 });
document.querySelectorAll('.reveal').forEach(element => observer.observe(element));

const form = document.querySelector('#inquiry-form');
form.addEventListener('submit', async event => { event.preventDefault(); const status = document.querySelector('#form-status'); const button = form.querySelector('button'); button.disabled = true; button.innerHTML = 'Transmitting...'; try { const response = await fetch('/api/inquiries', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(Object.fromEntries(new FormData(form))) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); status.textContent = result.message; status.className = 'form-status success'; form.reset(); } catch (error) { status.textContent = error.message || 'Could not transmit. Please try again.'; status.className = 'form-status error'; } finally { button.disabled = false; button.innerHTML = 'Transmit inquiry <span>↗</span>'; } });
